### ISSUE TITLE
DanielsTables3-00-00.xls

### ISSUE THREAD

**Issue by tomasztomys** [nkaczor/Zdrowix#3]
Myślę, że DanielsTables3-00-00.xls dostał się tutaj przez przypadek ;)

**Comment by kamilkazmierczak** [comment]
Też mnie ten plik zastanawia

**Comment by tomasztomys** [comment]
#4

**Comment by tomasztomys** [comment]
File was deleted in today commit. I'm glad I could help you @nkaczor :)
